services:
  # Serviço do Backend (Python/Django)
  - type: web
    name: srgo-backend
    env: python
    plan: free
    region: frankfurt # Exemplo de região, pode remover se não for necessário
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: "cd backend && gunicorn srgo.wsgi:application"
    healthCheckPath: /api/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: srgo-database # IMPORTANTE: Verifique se este é o nome do seu banco de dados
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - fromGroup: google-credentials # Assumindo que você criou um grupo de variáveis de ambiente

  # Serviço do Frontend (React - Servido como site estático)
  - type: static
    name: srgo-frontend
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: "./build"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: srgo-database
    databaseName: srgo_db # O nome interno do seu banco de dados
    plan: free
