services:
  # Serviço do Backend (Python/Django)
  - type: web
    name: srgo-backend
    env: python
    plan: free # Ou o seu plano atual
    buildCommand: ./render-build.sh
    startCommand: "cd backend && gunicorn srgo.wsgi:application"
    healthCheckPath: /api/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: srgo-database # Mude se o nome do seu banco de dados for diferente
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CREDENTIALS_JSON
        fromSecretFile:
          name: google-credentials
          key: GOOGLE_CREDENTIALS_JSON
    buildPacks:
      - url: https://github.com/heroku/heroku-buildpack-apt
    aptPackages:
      - libpango-1.0-0
      - libpangoft2-1.0-0
      - libgdk-pixbuf2.0-0

  # Serviço do Frontend (React - Servido como site estático)
  - type: static_site # --- CORREÇÃO APLICADA AQUI ---
    name: srgo-frontend
    plan: free # Ou o seu plano atual
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: "./build"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
