# Generated by Django 4.2.11 on 2025-08-05 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fato', models.DateTimeField()),
                ('descricao_fato', models.TextField()),
                ('fonte_informacao', models.CharField(max_length=200)),
                ('caderno_informativo', models.CharField(max_length=50)),
                ('evolucao_ocorrencia', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacaoCriminosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaEnvolvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_envolvimento', models.CharField(choices=[('VITIMA', 'Vítima'), ('TESTEMUNHA', 'Testemunha'), ('SUSPEITO', 'Suspeito'), ('AUTOR', 'Autor'), ('OUTRO', 'Outro')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envolvidos', to='ocorrencias.ocorrencia')),
                ('organizacao_criminosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='ocorrencias.organizacaocriminosa')),
            ],
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimentoPenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('vara_tribunal', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('EM_INVESTIGACAO', 'Em Investigação'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='EM_INVESTIGACAO', max_length=20)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('pessoa_envolvida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='ocorrencias.pessoaenvolvida')),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='tipo_ocorrencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.tipoocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
