# Generated by Django 4.2.11 on 2025-08-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(choices=[('Homicidio', 'Homicídio Doloso (CVLI)'), ('Resistencia', 'Auto de Resistência'), ('Refem', 'Crise com Refém'), ('Banco', 'Assalto a Banco'), ('Produtividade', 'Ação de Produtividade'), ('Social', 'Assunto Social'), ('Suplemento', 'Suplemento')], max_length=50)),
                ('data_fato', models.DateTimeField()),
                ('descricao_fato', models.TextField()),
                ('evolucao_ocorrencia', models.TextField(blank=True, null=True)),
                ('endereco_localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('regiao', models.CharField(blank=True, max_length=50, null=True)),
                ('fonte_informacao', models.CharField(blank=True, max_length=255, null=True)),
                ('caderno_informativo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacaoCriminosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_organizacao', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='Ativo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaEnvolvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('vulgo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('filiacao', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('tipo_envolvimento', models.CharField(choices=[('Vitima', 'Vítima (CVLI)'), ('Resistente', 'Resistente (Óbito)'), ('Autor', 'Autor/Envolvido'), ('Refem', 'Refém'), ('Testemunha', 'Testemunha')], max_length=50)),
                ('situacao_lesao', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedentes_resumo', models.TextField(blank=True, null=True)),
                ('caminho_foto', models.CharField(blank=True, max_length=255, null=True)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_envolvidas', to='ocorrencias.ocorrencia')),
                ('orcrim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.organizacaocriminosa')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimentoPenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_procedimento', models.CharField(max_length=100)),
                ('natureza_procedimento', models.CharField(blank=True, max_length=100, null=True)),
                ('unidade_origem', models.CharField(blank=True, max_length=255, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='ocorrencias.pessoaenvolvida')),
            ],
        ),
    ]
