# Generated by Django 5.0.6 on 2025-08-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ex: Taurus G2C, IMBEL MD2', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('FOGO', 'Arma de Fogo'), ('BRANCA', 'Arma Branca'), ('SIMULACRO', 'Simulacro'), ('ARTESANAL', 'Artesanal'), ('OUTRO', 'Outro')], default='FOGO', max_length=20)),
                ('marca', models.CharField(blank=True, help_text='Ex: Taurus, Glock, IMBEL', max_length=100)),
                ('calibre', models.CharField(blank=True, help_text='Ex: 9mm, .40, .380', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArmaApreendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('calibre', models.CharField(blank=True, max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('observacoes', models.TextField(blank=True)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas_apreendidas', to='ocorrencias.ocorrencia')),
                ('modelo_catalogado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.modeloarma', verbose_name='Modelo (do Catálogo)')),
            ],
        ),
    ]
