# Generated by Django 4.2.11 on 2025-08-05 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='endereco_localizacao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='organizacaocriminosa',
            name='nome_organizacao',
        ),
        migrations.RemoveField(
            model_name='organizacaocriminosa',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pessoaenvolvida',
            name='antecedentes_resumo',
        ),
        migrations.RemoveField(
            model_name='pessoaenvolvida',
            name='caminho_foto',
        ),
        migrations.RemoveField(
            model_name='pessoaenvolvida',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='pessoaenvolvida',
            name='documento_cpf',
        ),
        migrations.RemoveField(
            model_name='pessoaenvolvida',
            name='filiacao',
        ),
        migrations.RemoveField(
            model_name='pessoaenvolvida',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='pessoaenvolvida',
            name='orcrim',
        ),
        migrations.RemoveField(
            model_name='pessoaenvolvida',
            name='situacao_lesao',
        ),
        migrations.RemoveField(
            model_name='pessoaenvolvida',
            name='vulgo',
        ),
        migrations.RemoveField(
            model_name='procedimentopenal',
            name='natureza_procedimento',
        ),
        migrations.RemoveField(
            model_name='procedimentopenal',
            name='numero_procedimento',
        ),
        migrations.RemoveField(
            model_name='procedimentopenal',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='procedimentopenal',
            name='unidade_origem',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='organizacaocriminosa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacaocriminosa',
            name='nome',
            field=models.CharField(default='Padrão', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoaenvolvida',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoaenvolvida',
            name='nome',
            field=models.CharField(default='Padrão', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoaenvolvida',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoaenvolvida',
            name='organizacao_criminosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='ocorrencias.organizacaocriminosa'),
        ),
        migrations.AddField(
            model_name='procedimentopenal',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimentopenal',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='procedimentopenal',
            name='pessoa_envolvida',
            field=models.ForeignKey(default='Padrão', on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='ocorrencias.pessoaenvolvida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimentopenal',
            name='status',
            field=models.CharField(choices=[('EM_INVESTIGACAO', 'Em Investigação'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='EM_INVESTIGACAO', max_length=20),
        ),
        migrations.AddField(
            model_name='procedimentopenal',
            name='vara_tribunal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='evolucao_ocorrencia',
            field=models.TextField(default='Padrão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='fonte_informacao',
            field=models.CharField(default='Padrão', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoaenvolvida',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envolvidos', to='ocorrencias.ocorrencia'),
        ),
        migrations.AlterField(
            model_name='pessoaenvolvida',
            name='tipo_envolvimento',
            field=models.CharField(choices=[('VITIMA', 'Vítima'), ('TESTEMUNHA', 'Testemunha'), ('SUSPEITO', 'Suspeito'), ('AUTOR', 'Autor'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_ocorrencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.tipoocorrencia'),
        ),
    ]
