# Generated by Django 5.0.6 on 2025-08-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_modeloarma_armaapreendida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('coordenadoria', models.CharField(blank=True, max_length=255, verbose_name='COORPIN')),
            ],
        ),
        migrations.AddField(
            model_name='opm',
            name='aisp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opms', to='ocorrencias.aisp'),
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_bairro', models.CharField(max_length=255)),
                ('opm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.opm')),
            ],
        ),
        migrations.AddField(
            model_name='aisp',
            name='risp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisps', to='ocorrencias.risp'),
        ),
    ]
