# Generated by Django 5.0.6 on 2025-08-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_aisp_risp_opm_aisp_localidade_aisp_risp'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloarma',
            name='especie',
            field=models.CharField(choices=[('PISTOLA', 'Pistola'), ('REVOLVER', 'Revólver'), ('FUZIL', 'Fuzil'), ('ESPINGARDA', 'Espingarda'), ('METRALHADORA', 'Metralhadora'), ('SUBMETRALHADORA', 'Submetralhadora'), ('GRANADA', 'Granada'), ('EXPLOSIVO', 'Outros Explosivos'), ('NAO_DEFINIDA', 'Não Definida')], default='NAO_DEFINIDA', max_length=20, verbose_name='Espécie da Arma'),
        ),
        migrations.AddField(
            model_name='pessoaenvolvida',
            name='status',
            field=models.CharField(blank=True, choices=[('MORTO', 'Morto'), ('FERIDO', 'Ferido'), ('CAPTURADO', 'Capturado'), ('ILESO', 'Ileso'), ('NAO_APLICAVEL', 'Não Aplicável')], default='NAO_APLICAVEL', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoaenvolvida',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('RG', 'RG'), ('OUTRO', 'Outro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='armaapreendida',
            name='tipo',
            field=models.CharField(help_text='Ex: Arma de Fogo, Arma Branca...', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoaenvolvida',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento'),
        ),
    ]
