# Generated by Django 5.0.6 on 2025-08-08 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_modeloarma_especie_pessoaenvolvida_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='aisp_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.aisp', verbose_name='AISP da Área'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='foto_ocorrencia',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_ocorrencias/', verbose_name='Foto da Ocorrência'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='risp_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.risp', verbose_name='RISP da Área'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='tipo_homicidio',
            field=models.CharField(blank=True, choices=[('MASCULINA', 'Vítima Masculina'), ('FEMININA', 'Vítima Feminina (Feminicídio)'), ('CONFRONTO', 'Oposição à Intervenção Policial'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Tipo do Crime'),
        ),
    ]
