# Generated by Django 5.0.6 on 2025-08-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_ocorrencia_aisp_area_ocorrencia_foto_ocorrencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaenvolvida',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido')], default='I', max_length=1, null=True),
        ),
    ]
