# Generated by Django 5.0.6 on 2025-08-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0006_pessoaenvolvida_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_homicidio',
            field=models.CharField(blank=True, choices=[('CVLI', 'CVLI - Crimes Violentos Letais Intencionais'), ('FEMINICIDIO', 'Feminicídio'), ('LATROCINIO', 'Latrocínio (Roubo seguido de Morte)'), ('OPOSICAO_POLICIAL', 'Morte por Oposição à Intervenção Policial'), ('MORTE_A_ESCLARECER', 'Morte a Esclarecer'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Tipo do Crime'),
        ),
    ]
