# Generated by Django 5.0.6 on 2025-08-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0007_alter_ocorrencia_tipo_homicidio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadeCrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Modalidade')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_homicidio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.modalidadecrime', verbose_name='Tipo do Crime'),
        ),
    ]
