# Generated by Django 5.0.6 on 2025-08-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0008_modalidadecrime_alter_ocorrencia_tipo_homicidio'),
    ]

    operations = [
    ]
