# Generated by Django 5.0.6 on 2025-08-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0009_limpar_dados_homicidio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='foto_ocorrencia',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Foto da Ocorrência'),
        ),
    ]
